[project]
name = lxml_extras


[tox]
envlist = clean, py{39, 310, 311}
skipsdist = True
skip_missing_interpreters = True
sitepackages = False

[testenv:clean]
deps = coverage
skip_install = true
commands =
    ; hash -r
    coverage erase
    ; rm -Rf {toxinidir}/docs/_build {toxinidir}/docs/coverage {toxinidir}/docs/reports

[testenv]
passenv = *
allowlist_externals = *
install_command = "{envpython}" -m pip install -q {opts} {packages}
; envdir = {env:WORKON_HOME}/tox-{[project]name}/{envname}
sitepackages = False
; recreate = True
commands =
    # hash -r
    py{39, 310, 311}: "{envpython}" -m pytest --cov="{toxinidir}" --cov-append --cov-report=html:htmlcov --html=docs/reports/{envname}-report.html --json-report --json-report-file=docs/reports/{envname}-report.json {posargs}
deps =
    --editable=file:///{toxinidir}[test]
    --editable=file:///{toxinidir}

[testenv:lint]
sitepackages = False
; allowlist_externals = *
; recreate = True
deps = --editable=file:///{toxinidir}[lint]
commands =
    ; hash -r
    ; "{envpython}" -m flake8 {[project]name}
    ; "{envpython}" -m pylint {[project]name}
    "{envpython}" -m ruff check {toxinidir}
    "{envpython}" -m mypy {toxinidir}
    ; "{envpython}" -m black --check {[project]name} --diff
    ; "{envpython}" -m isort --check-only {[project]name}

[testenv:docs]
    sitepackages = False
    ; recreate = True
    deps = --editable=file:///{toxinidir}[docs]
    commands =
        ; hash -r
        stubgen -p {[project]name} --output docs/stubs
        sphinx-build -b html docs/source docs/_build/html -d docs/_build/doctrees -c docs
        sphinx-build -b coverage docs/source docs/_build/coverage -d docs/_build/doctrees  -c docs

