class XpathTooShortError(ValueError):
    def __init__(self, message: str = 'Invalid xpath: must have at least two valid parts') -> None: ...

class InvalidXpathAttributeError(ValueError):
    def __init__(self, message: str = 'Invalid xpath: attribute must be text() or @attribute') -> None: ...

class NoXpathAttributesfoundError(ValueError):
    def __init__(self, message: str = 'No attributes found') -> None: ...

class InvalidXpathError(ValueError):
    def __init__(self, message: str = 'Invalid xpath') -> None: ...

class StringifyError(ValueError):
    def __init__(self, message: str = 'Cannot stringify object') -> None: ...

class InvalidOnErrorValueError(ValueError):
    def __init__(self, message: str = 'Invalid value for OnError') -> None: ...
