from lxml.etree import _Element, _ElementTree
from lxml_extras.utils.enums import OnError as OnError
from lxml_extras.utils.exceptions import InvalidXpathAttributeError as InvalidXpathAttributeError, InvalidXpathError as InvalidXpathError, NoXpathAttributesfoundError as NoXpathAttributesfoundError, XpathTooShortError as XpathTooShortError
from lxml_extras.utils.misc import is_numeric as is_numeric
from typing import Any

def extract_attributes(tree: _Element | _ElementTree, xpath: str, *, default: Any | None = None, errors: OnError | str = ..., limit: int | None = None) -> list[str] | None: ...
def extract_links(tree: _Element | _ElementTree, xpath: str = '//a/@href', *, default: str | None = None, errors: OnError = ..., limit: int | None = None) -> list[str] | None: ...
def extract_images(tree: _Element | _ElementTree, xpath: str = '//img/@src', *, default: str | None = None, errors: OnError = ..., limit: int | None = None) -> list[str] | None: ...
def extract_first_image(tree: _Element | _ElementTree, xpath: str = '//img/@src', *, default: str | None = None, errors: OnError = ...) -> str | None: ...
