from collections.abc import Mapping
from lxml.etree import _ElementTree
from lxml_extras.extractors import extract_images as extract_images, extract_links as extract_links
from lxml_extras.utils.enums import OnError as OnError

def get_tree(url: str, *, params: Mapping[str, str] | None = None, headers: dict | None = None, timeout: int = 60) -> _ElementTree: ...
def scrape_images(url: str, xpath: str = '//img/@src', *, default: str | None = None, errors: OnError = ..., limit: int | None = None) -> list[str] | None: ...
def scrape_first_image(url: str, xpath: str = '//img/@src', *, default: str | None = None, errors: OnError = ...) -> str | None: ...
def scrape_links(url: str, xpath: str = '//a/@href', *, default: str | None = None, errors: OnError = ..., limit: int | None = None) -> list[str] | None: ...
def scrape_first_link(url: str, xpath: str = '//a/@href', *, default: str | None = None, errors: OnError = ...) -> str | None: ...
