name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tox
        run: python -m tox
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./docs/reports/
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: docs/reports/lcov.info
        

